# -*- coding: utf-8 -*-
"""telecom_churn_hw2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FMzrB9IR5oQCVM4zhWVSdu3sKgGSiLk

**2η Εργασία:** **Ανάλυση Αποχωρήσεων Πελατών (Customer Churn) σε Τηλεπικοινωνιακό Πάροχο με χρήση
Apache Spark**

**Θέμα 1: Φόρτωση, Έλεγχος και Καθαρισμός Δεδομένων**

1. Δημιουργία DataFrame
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, avg, lit, isnan, count
from pyspark.sql import functions as F
from pyspark.sql.functions import sum as spark_sum
import pandas as pd


spark = SparkSession.builder.appName("Telecom Churn Analysis").getOrCreate()
df = spark.read.csv("telecom_churn_10k.csv", header=True, inferSchema=True)

print("---  Φόρτωση & Έλεγχος Δεδομένων ---")
print("\nΠρώτες 10 γραμμές:")
df.show(10)

print("\nΣχήμα (Schema):")
df.printSchema()

total_records = df.count()
print(f"\nΣυνολικός αριθμός εγγραφών: {total_records}\n")

"""2. Έλεγχος ελλιπών τιμών (missing values)"""

print("--- Έλεγχος Ελλιπών Τιμών ---")

missing_counts_expr = [
    count(when(
        (col(c).isNull() | isnan(col(c))) if t in ("double", "float") else col(c).isNull(),
        c
    )).alias(c)
    for c, t in df.dtypes
]


df_missing_result = df.select(*missing_counts_expr)

missing_summary = df_missing_result.toPandas().transpose().reset_index()

missing_summary.columns = ['column_name', 'missing_count']

# Κρατάμε μόνο όσες στήλες έχουν κενά ( > 0 )
missing_summary = missing_summary[missing_summary['missing_count'] > 0]
missing_summary = missing_summary.sort_values(by='missing_count', ascending=False)

try:
    print("\nΣυγκεντρωτικός Πίνακας Ελλιπών Τιμών:")
    print(missing_summary.to_markdown(index=False))
except ImportError:
    print("\nΣυγκεντρωτικός Πίνακας Ελλιπών Τιμών (Standard Table):")
    print(missing_summary)

total_records = df.count()
print(f"\nΣημείωση: Συνολικές εγγραφές: {total_records} (10000 αναμενόμενο)")

"""3. Στρατηγική καθαρισμού"""

# Μετατροπή σε αριθμητικό και αφαίρεση ελλιπών τιμών στη μεταβλητή CHURN
df_cleaned = df.withColumn("TOTAL_CHARGES", col("TOTAL_CHARGES").cast("double"))


# Διαγραφή γραμμών όπου το CHURN είναι κενό
df_cleaned = df_cleaned.dropna(subset=["CHURN"])


# Υπολογισμός Διαμέσων στις στήλες που το να λείπει η τιμή μπορεί να αντικατασταθεί απο τη διάμεσο του συνόλου
numerical_cols = ['AGE', 'TENURE_MONTHS', 'MONTHLY_CHARGES', 'TOTAL_CHARGES']
median_values = {}

print("--- Υπολογισμός Διαμέσων ---")
for col_name in numerical_cols:

    median_val = df_cleaned.stat.approxQuantile(col_name, [0.5], 0.01)[0]
    median_values[col_name] = median_val
    print(f"Median for {col_name}: {median_val}")


# Αντικατάσταση των κενών με τους διαμέσους
df_clean = df_cleaned.fillna(median_values)


final_count = df_clean.count()
print(f"\nΤελικός αριθμός εγγραφών: {final_count}")


# Ελέγχουμε αν έμεινε κανένα κενό
missing_after_clean = df_clean.select([
    spark_sum(when(col(c).isNull() | isnan(col(c)), 1).otherwise(0)).alias(c)
    for c in numerical_cols + ['CHURN']
])

print("\nΈλεγχος Missing Values μετά το Imputation:")
missing_after_clean.show()

# Δημιουργία Temp View για τα επόμενα ερωτήματα SQL
df_clean.createOrReplaceTempView("temp_clean_data")

"""4. Βασική περιγραφική ανάλυση"""

print("\n--- Βασική Περιγραφική Ανάλυση ---")
analysis_cols = ["AGE", "TENURE_MONTHS", "MONTHLY_CHARGES", "TOTAL_CHARGES"]


print("\nΒασικά Στατιστικά (AGE, TENURE_MONTHS, MONTHLY_CHARGES, TOTAL_CHARGES):")
df_clean.select(analysis_cols).describe().toPandas().to_markdown(index=False)
df_clean.select(analysis_cols).describe().show()


# Μέσος όρος TENURE_MONTHS και MONTHLY_CHARGES ανά CHURN
print("\nΜέσος όρος TENURE_MONTHS και MONTHLY_CHARGES ανά CHURN (0: Active, 1: Churned):")
churn_agg_df = df_clean.groupBy("CHURN").agg(
    avg("TENURE_MONTHS").alias("Avg_Tenure_Months"),
    avg("MONTHLY_CHARGES").alias("Avg_Monthly_Charges")
).orderBy(col("CHURN").desc())

churn_agg_df.show()

"""5. Αρχικό Feature Engineering"""

from pyspark.sql.functions import sum, when, col, lit

print("\n--- Αρχικό Feature Engineering ---")

# Δημιουργία NUM_SERVICES (HAS_INTERNET + HAS_MOBILE + HAS_TV)
df_clean = df_clean.withColumn(
    "NUM_SERVICES",
    col("HAS_INTERNET") + col("HAS_MOBILE") + col("HAS_TV")
)

# Δημιουργία IS_LONG_TENURE (1 αν TENURE_MONTHS >= 24, αλλιώς 0)
df_clean = df_clean.withColumn(
    "IS_LONG_TENURE",
    when(col("TENURE_MONTHS") >= 24, lit(1)).otherwise(lit(0))
)

# AVG_CHARGE_PER_MONTH
df_clean = df_clean.withColumn(
    "AVG_CHARGE_PER_MONTH",
    when(col("TENURE_MONTHS") > 0, col("TOTAL_CHARGES") / col("TENURE_MONTHS"))
    .otherwise(col("MONTHLY_CHARGES"))
)

print("\nΔείγμα γραμμών με τα νέα πεδία (NUM_SERVICES, IS_LONG_TENURE, AVG_CHARGE_PER_MONTH):")
df_clean.select("CUSTOMER_ID", "TENURE_MONTHS", "MONTHLY_CHARGES",
                "TOTAL_CHARGES", "NUM_SERVICES", "IS_LONG_TENURE",
                "AVG_CHARGE_PER_MONTH", "CHURN").show(5)

df_clean.createOrReplaceTempView("churn_view")

"""**Θέμα 2: Ανάλυση με Spark SQL & Επιβεβαίωση Επιχειρησιακών Μοτίβων**

1. Δημιουργία προσωρινού view
"""

df_clean.createOrReplaceTempView("churn_view")

print("Το καθαρό DataFrame αποθηκεύτηκε ως temporary view με όνομα 'churn_view'.")

"""2. Βασικά ερωτήματα ανάλυσης churn"""

# 2.1. Churn ανά τύπο συμβολαίου
churn_by_contract = spark.sql("""
    SELECT CONTRACT_TYPE,
           COUNT(*) AS total_customers,
           SUM(CASE WHEN CHURN = 1 THEN 1 ELSE 0 END) AS churned_customers,
           ROUND(100.0 * SUM(CASE WHEN CHURN = 1 THEN 1 ELSE 0 END) / COUNT(*),2)
            AS churn_rate_percent
    FROM churn_view
    GROUP BY CONTRACT_TYPE
    ORDER BY churn_rate_percent DESC """)

churn_by_contract.show()

# 2.2. Churn ανά πλήθος υπηρεσιών

churn_by_services = spark.sql("""
    SELECT
        CASE
            WHEN NUM_SERVICES = 1 THEN '1 Service'
            WHEN NUM_SERVICES = 2 THEN '2 Services'
            ELSE '3+ Services'
        END AS service_group,
        COUNT(*) AS total_customers,
        SUM(CASE WHEN CHURN = 1 THEN 1 ELSE 0 END) AS churned_customers,
        ROUND(
            100.0 * SUM(CASE WHEN CHURN = 1 THEN 1 ELSE 0 END) / COUNT(*),
            2
        ) AS churn_rate_percent
    FROM churn_view
    GROUP BY
        CASE
            WHEN NUM_SERVICES = 1 THEN '1 Service'
            WHEN NUM_SERVICES = 2 THEN '2 Services'
            ELSE '3+ Services'
        END
    ORDER BY churn_rate_percent DESC
""")

churn_by_services.show()

# 2.3. Churn και μηνιαία χρέωση

avg_monthly_by_churn = spark.sql("""
    SELECT CHURN,ROUND(AVG(MONTHLY_CHARGES), 2) AS avg_monthly_charges
    FROM churn_view
    GROUP BY CHURN
    ORDER BY CHURN
    """)

avg_monthly_by_churn.show()

# 2.3 Μέση μηνιαία χρέωση ανά CHURN και CONTRACT_TYPE

avg_monthly_by_churn_contract = spark.sql("""
    SELECT CONTRACT_TYPE,CHURN,ROUND(AVG(MONTHLY_CHARGES), 2)
     AS avg_monthly_charges
    FROM churn_view
    GROUP BY CONTRACT_TYPE, CHURN
    ORDER BY CONTRACT_TYPE, CHURN
""")

avg_monthly_by_churn_contract.show()

"""3. Γεωγραφική ανάλυση (Top-Χ περιοχές)"""

churn_by_country = spark.sql("""
    SELECT COUNTRY, COUNT(*) AS total_customers,
        ROUND(100.0 * SUM(CASE WHEN CHURN = 1 THEN 1 ELSE 0 END) / COUNT(*),2)
        AS churn_rate_percent
    FROM churn_view
    GROUP BY COUNTRY
    HAVING COUNT(*) >= 100
    ORDER BY churn_rate_percent DESC
    LIMIT 5
""")
print("--Top-5 χώρες με το υψηλότερο ποσοστό churn--")
churn_by_country.show()

"""4. Έλεγχος των Hints του προβλήματος

Απο την ανάλυση churn hurn ανά τύπο συμβολαίου προκύπτει ότι
οι πελάτες με **Month-to-month** συμβόλαιο εμφανίζουν υψηλό ποσοστό αποχώρησης
(**53.21%**), σημαντικά μεγαλύτερο σε σύγκριση με τα συμβόλαια **One year** (**20.61%**) και **Two year** (**13.65%**). Το αποτέλεσμα αυτό δείχνει ότι η μικρή συμβατική δέσμευση αυξάνει σημαντικά την πιθανότητα churn, ενώ τα
μακροχρόνια συμβόλαια λειτουργούν προστατευτικά για τη διατήρηση πελατών.

Παράλληλα, η ανάλυση με βάση το πλήθος υπηρεσιών δείχνει ότι οι πελάτες με **μία μόνο υπηρεσία** εμφανίζουν το υψηλότερο churn (**47.98%**), ενώ το ποσοστό
μειώνεται για πελάτες με **δύο υπηρεσίες** (**37.38%**) και ακόμη περισσότερο
για πελάτες με **τρεις ή περισσότερες υπηρεσίες** (**26.84%**). Αυτό έχει σαν συμπέρασμα ότι τα πακέτα πολλαπλών υπηρεσιών αυξάνουν τη δέσμευση και μειώνουν την πιθανότητα αποχώρησης.

Τέλος, από τη σύγκριση της μέσης μηνιαίας χρέωσης παρατηρείται ότι οι πελάτες που
αποχωρούν έχουν, κατά μέσο όρο, **υψηλότερες MONTHLY_CHARGES** σε σχέση με τους
ενεργούς πελάτες. Συμπερασματικά αυτό υποδηλώνει ότι το αυξημένο κόστος αποτελεί σημαντικό
παράγοντα δυσαρέσκειας και ενισχύει την πιθανότητα churn, ειδικά όταν συνδυάζεται με
χαμηλή συμβατική δέσμευση.

**Θέμα 3: Πρόβλεψη Μηνιαίας Χρέωσης με Decision Tree για δυναμική τιμολόγηση**

1. Ορισμός συνόλου χαρακτηριστικών (features) και στόχου (label)
"""

label_col = "MONTHLY_CHARGES"

feature_cols = [
    "AGE",
    "TENURE_MONTHS",
    "NUM_COMPLAINTS",
    "SUPPORT_CALLS",
    "HAS_INTERNET",
    "HAS_MOBILE",
    "HAS_TV",
    "NUM_SERVICES",
    "CONTRACT_TYPE",
    "PAYMENT_METHOD",
    "COUNTRY"
]

# Δημιουργία DataFrame μόνο με features + label
df_ml = df_clean.select(feature_cols + [label_col])

print("Δημιουργήθηκε DataFrame για τα παραπάνω features + label")
df_ml.show(5)

"""2. Προεπεξεργασία & Pipeline"""

from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, OneHotEncoder, VectorAssembler
from pyspark.ml.regression import DecisionTreeRegressor

# Κατηγορικά πεδία
categorical_cols = ["CONTRACT_TYPE", "PAYMENT_METHOD", "COUNTRY"]

# Δημιουργία StringIndexers
indexers = [
    StringIndexer(
        inputCol=col,
        outputCol=col + "_indexed",
        handleInvalid="keep" # Αποφυγή runtime errors
    )
    for col in categorical_cols
]

# OneHotEncoder για τα indexed πεδία (κρατάμε ένα encoder για όλα)
encoder = OneHotEncoder(
    inputCols=[c + "_indexed" for c in categorical_cols],
    outputCols=[c + "_encoded" for c in categorical_cols]
)

# Αριθμητικά / δυαδικά χαρακτηριστικά
numeric_cols = [
    "AGE",
    "TENURE_MONTHS",
    "NUM_COMPLAINTS",
    "SUPPORT_CALLS",
    "HAS_INTERNET",
    "HAS_MOBILE",
    "HAS_TV",
    "NUM_SERVICES"
]

# VectorAssembler (Όλα τα τελικά features)
assembler_inputs = numeric_cols + [c + "_encoded" for c in categorical_cols]

assembler = VectorAssembler(
    inputCols=assembler_inputs,
    outputCol="features"
)

# Ορισμός Decision Tree Regressor
dt_regressor = DecisionTreeRegressor(
    labelCol="MONTHLY_CHARGES",
    featuresCol="features",
    maxDepth=5, # αποφεύγουμε overfitting
    seed=42
)

# Δημιουργία Pipeline(indexers → (encoder) → assembler → decision tree regressor)
pipeline = Pipeline(
    stages=indexers + [encoder, assembler, dt_regressor]
)

print("Το Spark ML Pipeline δημιουργήθηκε επιτυχώς.")

"""3. Εκπαίδευση και αξιολόγηση"""

# Διαχωρισμός σε training και test set

train_df, test_df = df_ml.randomSplit([0.7, 0.3], seed=42)

print(f"Training set size: {train_df.count()}")
print(f"Test set size: {test_df.count()}")

# Εκπαίδευση μοντέλου
pipeline_model = pipeline.fit(train_df)

# Παραγωγή προβλέψεων στο test set
predictions = pipeline_model.transform(test_df)

# Εμφάνιση δείγματος προβλέψεων
predictions.select(
    "MONTHLY_CHARGES", "prediction"
).show(5)

# Υπολογισμός μετρικών
from pyspark.ml.evaluation import RegressionEvaluator

# RMSE (Μέσο σφάλμα πρόβλεψης σε ευρώ)
rmse_evaluator = RegressionEvaluator(
    labelCol="MONTHLY_CHARGES",
    predictionCol="prediction",
    metricName="rmse"
)

rmse = rmse_evaluator.evaluate(predictions)

# R²
r2_evaluator = RegressionEvaluator(
    labelCol="MONTHLY_CHARGES",
    predictionCol="prediction",
    metricName="r2"
)

r2 = r2_evaluator.evaluate(predictions)

print("--Εμφάνηση τιμών Μετρικών--\n")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.3f}")